### ISSUE TITLE
"Not Found Page" Time Out

### ISSUE THREAD

**Issue by imJoeFi** [tvolk131/lightning_vend#72]
Caught the error:

in.b40a5844b93c48eab63c.js:102 TypeError: t.nullCommands is not iterable
    at main.b40a5844b93c48eab63c.js:102:537692
    at main.b40a5844b93c48eab63c.js:102:498367
    at ol (main.b40a5844b93c48eab63c.js:102:343103)
    at ku (main.b40a5844b93c48eab63c.js:102:363225)
    at main.b40a5844b93c48eab63c.js:102:359829
    at S (main.b40a5844b93c48eab63c.js:102:468927)
    at MessagePort.R (main.b40a5844b93c48eab63c.js:102:469459)
fs @ main.b40a5844b93c48eab63c.js:102
(anonymous) @ main.b40a5844b93c48eab63c.js:102
Fi @ main.b40a5844b93c48eab63c.js:102
xl @ main.b40a5844b93c48eab63c.js:102
wl @ main.b40a5844b93c48eab63c.js:102
bl @ main.b40a5844b93c48eab63c.js:102
(anonymous) @ main.b40a5844b93c48eab63c.js:102
Su @ main.b40a5844b93c48eab63c.js:102
uu @ main.b40a5844b93c48eab63c.js:102
Uo @ main.b40a5844b93c48eab63c.js:102
ku @ main.b40a5844b93c48eab63c.js:102
(anonymous) @ main.b40a5844b93c48eab63c.js:102
S @ main.b40a5844b93c48eab63c.js:102
R @ main.b40a5844b93c48eab63c.js:102
main.b40a5844b93c48eab63c.js:102 React Router caught the following error during render TypeError: t.nullCommands is not iterable
    at main.b40a5844b93c48eab63c.js:102:537692
    at main.b40a5844b93c48eab63c.js:102:498367
    at ol (main.b40a5844b93c48eab63c.js:102:343103)
    at ku (main.b40a5844b93c48eab63c.js:102:363225)
    at main.b40a5844b93c48eab63c.js:102:359829
    at S (main.b40a5844b93c48eab63c.js:102:468927)
    at MessagePort.R (main.b40a5844b93c48eab63c.js:102:469459) {componentStack: '\n    at https://lightningvend.com/main.b40a5844b93…vend.com/main.b40a5844b93c48eab63c.js:102:137466)'}
c

**Comment by tvolk131** [comment]
Thanks for posting that error! That is hugely helpful. A search in the code for `.nullCommands` yields just two results:

https://github.com/tvolk131/lightning_vend/blob/c9d6070dee34d6da7571ab25c9c356add2f255a3/frontend/shared/commandExecutor.ts#L11

https://github.com/tvolk131/lightning_vend/blob/c9d6070dee34d6da7571ab25c9c356add2f255a3/frontend/server/clientApi/deviceSocketManager.ts#L319

I'm still not entirely certain what's happening, but this narrows down the problem significantly.

**Comment by tvolk131** [comment]
The first place that stands out to me as the potential source of the issue is here:

https://github.com/tvolk131/lightning_vend/blob/c9d6070dee34d6da7571ab25c9c356add2f255a3/frontend/client/src/devicePage.tsx#L39-L53

Where we cast the response of an HTTP request as a particular Typescript type, without actually checking if the types match. Even if this isn't causing the problem above, this is still something we should fix.
